### ISSUE TITLE
Regarding errors that occur in the final train step at mococifar10_lightly.ipynb

### ISSUE THREAD

**Issue by gymoon10** [smartdanny/MoCoV2_CIFAR10#1]
Hi, I am a graduate student studying computer vision and thank you so much for sharing a MoCoV2 code.  The materials you provided  was really helpful to me.

However, I opened the issue because I wanted to ask a question about the 'mococifar10_lightly.ipynb'.

At 'Final train'  step, when I define the classifier with trained backbone weights the following error occurs. (clf = model.Classifier(mocomodel.resnet_moco, max_epochs=25))
AttributeError: 'MocoModel' object has no attribute 'Classifier' 

The only difference is that I used the newer version of pytorch_lightning(1.5.10) and lightly(1.2.7). In addition, I also used torchmetrics(0.7.2) for the part of 'self.accuracy=torchmetrics.Accuracy()' at the Classifier of 'moco_model.py'.

This is the link to the ipynb file I used for studying.
https://github.com/gymoon10/Computer-Vision-Practice/blob/main/MoCo/MoCoV2_CIFAR10.ipynb

I'm sorry to trouble you, but I'd appreciate your cooperation. Once again thank you for providing high-quality learning contents and programming code.

**Comment by shatz01** [comment]
Im happy this is useful to someone :)

The classifier is from `moco_model.py`. I never really tested this repo before uploading it so I probably just forgot to import it. You should be able to do `from moco_model import Classifer` or something like that and it will work. If I have time later this week ill make this repo better.

In any case good luck with your research and let me know if you run into more issues.

**Comment by gymoon10** [comment]
I solved the problem by importing `moco_model.py` and confirmed that training of  ` clf` also works well. It seems that the problem was `Classifier` and `MocoModel` of `moco_model.py` were defined on different jupyter notebook shells.

Thank you
